<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
?>

<?php echo $this->pageTitle($translate('Items'), 2); ?>

<div class="browse-controls">
    <div class="pagination-container">
        <?php echo $this->pagination(); ?>
    </div>

    <div class="sort-container">
        <?php echo $this->sortSelector([
            'created' => ['label' => $translate('Created'), 'value' => 'created'],
            'dcterms:title' => ['label' => $translate('Title'), 'value' => 'dcterms:title']
        ]); ?>
        <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    </div>
</div>

<ul class="resource-list grid-layout">
    <?php foreach ($items as $item): ?>
        <?php if (!empty($item->media())): ?>
            <li class="item resource">
                <div class="photo-frame">
                    <?php echo $item->linkRaw($this->thumbnail($item, 'medium')); ?>
                </div>
                <div class="item-metadata">
                    <h4><?php echo $item->link($item->displayTitle()); ?></h4>
                    <?php if ($description = $item->displayDescription()): ?>
                    <div class="description"><?php echo $escape($description); ?></div>
                    <?php endif; ?>
                </div>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>

<div class="browse-footer-nav">
    <?php echo $this->pagination(); ?>
</div>