[info]
name         = "The Fifty Acres"
version      = "1.1"
author       = "Liz Casler Loomans"
description  = "A custom scrapbook-style theme with fixed sidebar and hero banner."
theme_link   = "https://github.com/Liziloo/the-fifty-acres"
author_link  = "https://thefiftyacres.com/"
omeka_version_constraint = "^4.2.0"

[config]
elements.logo.name = "logo"
elements.logo.type = "Omeka\Form\Element\Asset"
elements.logo.options.label = "Logo"

elements.banner.name = "banner"
elements.banner.type = "Omeka\Form\Element\Asset"
elements.banner.options.label = "Banner"

elements.croppedbanner.name = "croppedbanner"
elements.croppedbanner.type = "Omeka\Form\Element\Asset"
elements.croppedbanner.options.label = "Cropped Banner"

elements.footer.name = "footer"
elements.footer.attributes.id = "footer"
elements.footer.type = "Omeka\Form\Element\HtmlTextarea"
elements.footer.options.label = "Footer Content"
elements.footer.options.info = "HTML content to appear in the footer"
elements.footer.attributes.value = "Powered by Omeka S"

; Resource Page Regions
resource_page_regions.items.main = "Main Content"
resource_page_regions.items.sidebar = "Scrapbook Sidebar"
resource_page_regions.item_sets.main = "Main Content"
resource_page_regions.media.main = "Main Content"

; Default Resource Page Blocks
resource_page_blocks.items.sidebar[] = "values"
resource_page_blocks.items.main[] = "mediaEmbeds"
resource_page_blocks.items.main[] = "itemSets"
resource_page_blocks.items.main[] = "mediaList"
resource_page_blocks.items.main[] = "linkedResources"
resource_page_blocks.item_sets.main[] = "values"
resource_page_blocks.media.main[] = "mediaRender"
resource_page_blocks.media.main[] = "values"

block_templates.asset.asset-3-grid = "3 column grid"
block_templates.media.media-card = "2 column cards"
block_templates.media.cabinet-card = "Cabinet Card (Narrative)"
block_templates.browsePreview.cabinet-grid = "Cabinet Card Grid"

page_templates.portrait-narrative = "Portrait Narrative"
page_templates.portrait-family = "Family Portrait Narrative"
