<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));

// Theme Assets
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();

$pageTemplate = isset($page) ? $page->layoutDataValue('template_name') : '';
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

<?php echo $this->htmlElement('body'); ?>
    <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>

    <div class="container">
        <?php echo $userBar; ?>

        <div class="sidebar">
            <div class="sidebar-header">
                <a href="<?php echo $site->url(); ?>" class="site-emblem">
                    <?php if ($this->themeSetting('logo')): ?>
                        <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                    <?php else: ?>
                        <div class="default-emblem">H</div>
                    <?php endif; ?>
                </a>
            </div>

            <nav id="vertical-nav">
                <button type="button" id="mobile-nav-toggle" aria-label="Open navigation menu">
                </button>
                <?php echo $site->publicNav()->menu()->renderMenu(); ?>

                <div class="search">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
            </nav>
        </div>

            <div class="main">

                <?php
                $isHero = (isset($pageTemplate) && strpos($pageTemplate, 'page-with-hero') !== false);
                $assetName = $isHero ? 'banner' : 'croppedbanner';
                ?>

                <div class="hero-banner">
                    <?php if ($banner = $this->themeSettingAssetUrl($assetName)): ?>
                        <img src="<?php echo $banner; ?>" alt="The Fifty Acres Banner" />
                    <?php endif; ?>
                </div>

                <main class="content" role="main">
                    <?php echo $this->content; ?>
                </main>
                <footer>
                    <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                    <?php else: ?>
                        <?php echo $this->translate('Powered by Omeka S'); ?>
                    <?php endif; ?>
                </footer>
            </div>

        </div>
    </body>
</html>